version: 1.0.0-prerelease-{build}
configuration: Release
image: Visual Studio 2019
environment:
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
    NUGET_API_KEY:
        secure: MYKEY
dotnet_csproj:
    patch: true
    file: '**\*.csproj'
    version: '{version}'
    package_version: '{version}'
    assembly_version: '{version}'
    file_version: '{version}'
    informational_version: '{version}'
nuget:
    account_feed: false
    project_feed: false
    disable_publish_on_pr: true
init:
  - git config --global core.autocrlf input
before_build:
    appveyor-retry dotnet restore --verbosity minimal
build:
    project: Backblaze B2.sln
    verbosity: minimal
build_script:
#    - dotnet build "src\Client\Backblaze.Client.csproj" -c %CONFIGURATION% --no-dependencies /p:Version=%APPVEYOR_BUILD_VERSION%
#    - dotnet build "src\Agent\Backblaze.Agent.csproj" -c %CONFIGURATION% --no-dependencies /p:Version=%APPVEYOR_BUILD_VERSION%
#    - dotnet build "src\Cmdlet\Backblaze.Cmdlet.csproj" -c %CONFIGURATION% --no-dependencies /p:Version=%APPVEYOR_BUILD_VERSION%
test: on
test_script:
    - dotnet test "test\Unit\Backblaze.Tests.Unit.csproj" -c %CONFIGURATION%
after_test:
    - dotnet pack "src\Client\Backblaze.Client.csproj" -c %CONFIGURATION% --no-build --include-symbols -p:SymbolPackageFormat=snupkg /p:Version=%APPVEYOR_BUILD_VERSION% -o %APPVEYOR_BUILD_FOLDER%\artifacts
    - dotnet pack "src\Agent\Backblaze.Agent.csproj" -c %CONFIGURATION% --no-build --include-symbols -p:SymbolPackageFormat=snupkg /p:Version=%APPVEYOR_BUILD_VERSION% -o %APPVEYOR_BUILD_FOLDER%\artifacts
artifacts:
    - path: .\artifacts\**\*.nupkg
      name: NuGet
    - path: .\artifacts\**\*.snupkg
      name: NuGetSymbols
deploy_script:
    - dotnet nuget push %APPVEYOR_BUILD_FOLDER%\artifacts\Backblaze.Client.%APPVEYOR_BUILD_VERSION%.nupkg -s https://api.nuget.org/v3/index.json -k %NUGET_API_KEY%
    - dotnet nuget push %APPVEYOR_BUILD_FOLDER%\artifacts\Backblaze.Agent.%APPVEYOR_BUILD_VERSION%.nupkg -s https://api.nuget.org/v3/index.json -k %NUGET_API_KEY%
