on:
  push:
    paths-ignore:
      - 'changelog.md'
      - 'readme.md'
    branches:
      - master
    tags:
      - v.[0-9]+.[0-9]+.[0-9]+
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
jobs:
  Build:
    name: Build on ${{ matrix.dotnet }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        configuration: ['Release']
        verbosity: ['Minimal']
        os: [windows-latest]
        dotnet: ['3.0.100']
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup .Net Core - ${{ matrix.dotnet }}@${{ matrix.os }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Run Build
      run: dotnet build --verbosity ${{ matrix.verbosity }} --configuration ${{ matrix.configuration }}
    - name: Run Tests
      run: dotnet test test/unit/Backblaze.Tests.Unit.csproj --verbosity  ${{ matrix.verbosity }} --configuration ${{ matrix.configuration }} --no-build --results-directory artifacts --logger:trx
      env:
        Agent__ApplicationKey: ${{ secrets.AGENT_APPLICATION_KEY }}
        Agent__KeyId: ${{ secrets.AGENT_KEY_ID }}
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: Results
        path: artifacts
  Release:
    name: Release on ${{ matrix.dotnet }}
    runs-on: ${{ matrix.os }}
    needs: [Build]
    if: github.event.action == 'published'
    strategy:
      matrix:
        configuration: ['Release']
        verbosity: ['Minimal']
        os: [windows-latest]
        dotnet: ['3.0.100']
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup .Net Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}             
    - name: Pack Nuget
      run: dotnet pack --verbosity ${{ matrix.verbosity }} --configuration ${{ matrix.configuration }} --include-symbols -p:SymbolPackageFormat=snupkg --output artifacts
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: Packages
        path: artifacts
#    - name: Publish Package to GitHub
#      run: dotnet nuget push artifacts/*.nupkg -s "https://nuget.pkg.github.com/microcompiler/index.json" -k ${{ secrets.GITHUB_TOKEN }}
#    - name: Publish Package to Nuget
#      run: dotnet nuget push artifacts/*.* -s "https://api.nuget.org2/v3/index.json" -k ${{ secrets.NUGET_API_KEY }}
