name: Actions CI

on:
  push:
    branches: [ master, main ]
    paths: 
      - '**'
      - '!.editorconfig'
      - '!.gitattributes'
      - '!.gitignore'
      - '!*.md'
      - '!LICENSE'
env:
  VERBOSITY: 'Minimal'
  CONFIGURATION: 'Release'
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

jobs: 
  Build:
    name: Build on .NET Core ${{ matrix.dotnet }}    
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        dotnet: ['3.1.402']
    
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Extract build and copyright information into variables
      id: info
      run: |
        echo "##[set-output name=build;]$(echo $(git rev-list --count HEAD))"
        echo "##[set-output name=copyright;]$(echo © $(date -u +%Y) Bytewizer.  All rights reserved.)"

    - name: Show build information
      run: |
        echo build=${{ steps.info.outputs.build }}
        echo copyright=${{ steps.info.outputs.copyright }}

    - name: Setup .NET Core 
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
      
    - name: Show .NET Core information
      run: dotnet --info
            
    - name: Build and test project
      run: >-
        dotnet test -p:BuildNumber="${{ steps.info.outputs.build }}" -p:Copyright="${{ steps.info.outputs.copyright }}"
        --verbosity ${VERBOSITY}  
        --configuration ${CONFIGURATION} 
        --results-directory .builds/artifacts 
        --logger:trx
      env:
        Agent__ApplicationKey: ${{ secrets.AGENT_APPLICATION_KEY }}
        Agent__KeyId: ${{ secrets.AGENT_KEY_ID }}   

    - name: Build and pack project
      run: >- 
        dotnet pack -p:BuildNumber="${{ steps.info.outputs.build }}" -p:Copyright="${{ steps.info.outputs.copyright }}"
        --version-suffix prebuild.${{ steps.info.outputs.build }}
        --verbosity ${VERBOSITY}
        --configuration ${CONFIGURATION}
        --include-symbols
        --output .builds/artifacts
         
    - name: Upload build artifacts
      uses: actions/upload-artifact@v1
      with:
        name: Build Package
        path: .builds/artifacts
