on:
  push:
    branches:
      - master
    tags:
      - v.[0-9]+.[0-9]+.[0-9]+
env:
  VERBOSITY: Minimal
  CONFIGURATION: Release
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
jobs:
  Build:
    name: Build on ${{ matrix.dotnet }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        dotnet: ['3.0.100']
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup .Net Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Run Build
      run: dotnet build --verbosity ${{ env:VERBOSITY }} --configuration ${{ env:CONFIGURATION }}
    - name: Run Tests
      run: dotnet test test/unit/Backblaze.Tests.Unit.csproj --verbosity  Minimal --configuration Release --no-build --results-directory artifacts --logger:trx
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: Results
        path: artifacts
  Release:
    name: Release on ${{ matrix.dotnet }}
    runs-on: ${{ matrix.os }}
    needs: [build]
    if: github.event_name == 'push'
    strategy:
      matrix:
        os: [windows-latest]
        dotnet: ['3.0.100']
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup .Net Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}             
    - name: Pack Nuget
      run: dotnet pack --verbosity  Minimal --configuration Release --include-symbols -p:SymbolPackageFormat=snupkg --output artifacts
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: Packages
        path: artifacts
#      - name: Publish Package to GitHub
#        run: dotnet nuget push ./artifacts/packages/*.nupkg -s "https://nuget.pkg.github.com/microcompiler/index.json" -k ${GITHUB_TOKEN}  
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish Package to Nuget
      run: dotnet nuget push ./artifacts/packages/*.* -s "https://api.nuget.org2/v3/index.json" -k ${ NUGET_API_KEY }  
      env:
        GITHUB_TOKEN: ${{ secrets.NUGET_API_KEY }}
