name: Github Actions CI

on: [push]

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

jobs:
  release:
    name: Release
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup .Net Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.0.100
      - name: Build
        run: dotnet build --verbosity Minimal --configuration Release
      - name: Test
        working-directory: ./test/unit
        run: dotnet test Backblaze.Tests.Unit.csproj --verbosity  Minimal --configuration Release --no-build
      - name: Pack Nuget
        run: dotnet pack --verbosity  Minimal --configuration Release --no-build --include-symbols -p:SymbolPackageFormat=snupkg -o ./artifacts/
      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Packages
          path: ./artifacts/
      - name: Publish Nuget to GitHub registry
        run: |
           for f in ./artifacts/*.nupkg
           do
             curl -vX PUT -u "microcompiler:${{ secrets.GHPackagesToken }}" -F package=@$f https://nuget.pkg.github.com/[microcompiler]/
           done
        shell: bash
      - name: Release
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: true
