on:
  push:
    branches:
      - master
    tags:
      - v.[0-9]+.[0-9]+.[0-9]+
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
jobs:
  Build:
    name: Build on ${{ matrix.dotnet }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        dotnet: ['3.0.100']
        os: [ubuntu-latest, windows-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup .Net Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Run Build
      run: dotnet build --verbosity Minimal --configuration Release
    - name: Run Test
      run: dotnet test ./test/unit/Backblaze.Tests.Unit.csproj --verbosity  Minimal --configuration Release --no-build --results-directory ./artifacts --logger:trx
    - name: Upload Logs Artifact
      uses: actions/upload-artifact@v1
      with:
        name: Logs
        path: ./artifacts
